### ISSUE TITLE
Design area's not saved

### ISSUE THREAD

**Issue by nielsvr** [radishconcepts/woocommerce-naguro-connect#84]
I can't seem be able to save a design area at all;

- Storefront with child theme, WooCommerce and Naguro
- After setting up a design area and clicking publish, the area is removed
- No other plugins are activated

Doesn't work either with just Storefront without child theme.

For a live test environment contact me

**Comment by coenjacobs** [comment]
Sorry for the late reply. Found out I wasn't watching this repository. :confused: 

Anyway, does this only happen with the Storefront theme?

**Comment by nielsvr** [comment]
No worries!

No, happens with TwentyFifteen too. Weird right? It's pretty basic setup. I can give you access if you want to check it out yourselves.

**Comment by coenjacobs** [comment]
Can you confirm other meta (from WooCommerce, like price, inventory etc, for example) does get saved? I can't reproduce it on my end. Can you provide details like PHP/server versions? What version of WordPress, WooCommerce and WooCommerce Naguro Connect plugin are you on?

**Comment by nielsvr** [comment]
Yes, all other meta gets saved (prices, SKU, categories, content)

WordPress: 4.2.2
WooCommerce: 2.3.9 
Naguro: 1.1.1
MySQL 5.6.22
PHP 5.6.4 on Apache 2.4.10

**Comment by nielsvr** [comment]
Hi @coenjacobs,

Can you look at it? My license feels kinda useless at the moment ;). Feel free to e-mail me to get access to the site.

**Comment by coenjacobs** [comment]
Sorry, things have been hectic. I just emailed you.
